--Login TABLE --
CREATE TABLE LOGINACCOUNT (ID VARCHAR2(30) PRIMARY KEY, PASSWORD VARCHAR2(30));
--Master accouont--
INSERT INTO LOGINACCOUNT VALUES('cafemaster', 'coffee');

--Member TABLE-- 
CREATE TABLE MEMBER (
MEMBERNO NUMBER(5) UNIQUE,
TELNO VARCHAR2(20) PRIMARY KEY,
MEMBERNAME VARCHAR2(30) NOT NULL,
MBONUS NUMBER DEFAULT 0
);
--Member SEQUENCE--
CREATE SEQUENCE MEMBER_SEQ START WITH 1 INCREMENT BY 1;
--Member required data-
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, '9999', '비회원',0);

--Menu TABLE--
CREATE TABLE MENU (
MENUNO NUMBER(5) PRIMARY KEY,
MNAME VARCHAR2(25),
MPRICE NUMBER NOT NULL,
MORIGINALPRICE NUMBER NOT NULL);

--Menu SEQUENCE—
CREATE SEQUENCE MENU_SEQ START WITH 1 INCREMENT BY 1;
--Order TABLE--
CREATE TABLE ORDERS(
ORDERNO NUMBER(5) PRIMARY KEY,
MENUNO NUMBER(5),
COUNT NUMBER(5) NOT NULL,
TOTAL NUMBER ,
TELNO VARCHAR2(20),
USEBONUS NUMBER(1), 
TIME DATE
);

--Order SEQUENCE--
CREATE SEQUENCE ORDERS_SEQ
START WITH 1 INCREMENT BY 1;
--Sale TABLE --
CREATE TABLE SALE (
SALEDATE DATE PRIMARY KEY,
MENULIST VARCHAR2(4000),
TOTALSALE NUMBER,
ORIGINALSALE NUMBER);
--제약조건-- 
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_MENU FOREIGN KEY (MENUNO) REFERENCES MENU(MENUNO) ON DELETE CASCADE;
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_TELNO FOREIGN KEY (TELNO) REFERENCES MEMBER(TELNO) ON DELETE CASCADE;
COMMIT;
